[server]
fileWatcherType = "auto"
port = 8501
headless = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
fastReruns = true
magicEnabled = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[ui]
hideTopBar = false